name: Simple Todos
schema: "1.0"
version: "1.0.0"
git: https://github.com/isotropy/simple-todos
services:
  - name: server
    type: http
    build:
      - static
      - client
      - server
    locations:
      - location: /
        type: nodejs
        main: /server/index.js
      - location: /static
        type: static
        path: /static
builds:
  - name: static
    type: copy
    dest: /static
  - name: client
    type: typescript
    bundle: yes
    output: /static/client.js
  - name: server
    type: typescript
    output: /server
    connections:
      - type: webdisk
        path: ./disk.ts
        disk: todos
      - type: postgres
        path: ./db.ts
        db: todosdb
      - type: redis
        path: ./redis.ts
        db: todoscache
